let activitiesView='teacher';
let selectedActivityStudent='';
let activeActivityId=null
let activeTaskStartedAt=null;

const activityTypes={
  oral:{label:'Lectura oral',icon:'◖',summary:'Leé en voz alta un texto breve con acompañamiento docente.',title:'Lectura en la plaza',prompt:'Leé este texto en voz alta. Cuando termines, marcá la casilla para registrar que completaste la lectura.',text:'El sábado, Clara fue a la plaza con su abuelo. Llevaron una pelota roja y una botella de agua. Cerca de los árboles encontraron a Tomás, que estaba armando un barrilete. Los tres jugaron hasta que el sol empezó a bajar. Antes de volver a casa, Clara guardó la pelota en su mochila y saludó a su nuevo amigo.'},
  comprehension:{label:'Comprensión lectora',icon:'▤',summary:'Leé un texto y respondé preguntas sobre lo que cuenta.',title:'La biblioteca del barrio',prompt:'Leé el texto con atención y elegí una respuesta para cada pregunta.',text:'Cada miércoles, Julia visita la biblioteca del barrio. Allí puede elegir libros para llevar a casa durante una semana. Esta vez encontró un libro sobre aves viajeras. La bibliotecaria le recomendó anotar las preguntas que le surgieran mientras leía. Julia guardó el libro en su mochila y salió pensando en las golondrinas.'},
  writing:{label:'Producción escrita',icon:'✎',summary:'Escribí un texto propio a partir de una consigna.',title:'Una tarde para recordar',prompt:'Contá una tarde que recuerdes con cariño. ¿Dónde estabas? ¿Con quién? ¿Qué pasó? Escribí un texto propio con tus ideas.'},
  math:{label:'Pensamiento matemático',icon:'▦',summary:'Resolvé desafíos numéricos y registrá tus procedimientos.',title:'Desafíos con números',prompt:'Resolvé cada cuenta. Si querés, anotá en observaciones cómo pensaste cada respuesta.'}
};
const activityQuestions=[
  {key:'q1',text:'¿Cada cuánto visita Julia la biblioteca?',options:[['weekly','Todos los miércoles'],['daily','Todos los días'],['monthly','Una vez al mes']],answer:'weekly'},
  {key:'q2',text:'¿Qué tema tenía el libro que eligió?',options:[['oceans','Los océanos'],['birds','Las aves viajeras'],['plants','Las plantas del barrio']],answer:'birds'},
  {key:'q3',text:'¿Qué le recomendó la bibliotecaria?',options:[['draw','Dibujar la biblioteca'],['questions','Anotar las preguntas que surgieran'],['return','Devolver el libro ese día']],answer:'questions'}
];
const mathQuestions=[['m1','18 + 27',45],['m2','63 − 28',35],['m3','6 × 4',24],['m4','32 ÷ 4',8]];
function activityCard(type){const item=activityTypes[type];return `<article class="activity-type-card"><div class="activity-type-icon ${type}">${item.icon}</div><span class="activity-level">MODELO · PRIMARIA</span><h3>${item.label}</h3><p>${item.summary}</p><button class="button secondary small" data-assign-type="${type}">＋ Asignar actividad</button></article>`}
function setActivitiesView(view){activitiesView=view;activeActivityId=null;render()}
function activitiesPage(){return `${heading('Actividades','Consignas para practicar y compartir entre docentes y estudiantes.',`<span class="status-chip neutral">${AulaClaraState?.cloudSession?'CONECTADO':'PROTOTIPO LOCAL'}</span>`)}<div class="activity-demo-notice"><b>Espacio de prueba.</b> Elegí una vista para recorrer la experiencia docente o estudiante. ${AulaClaraState?.cloudSession?'Las actividades y entregas se sincronizan con el colegio. La vista estudiante sigue siendo una simulación bajo la cuenta docente.':'Las tareas y entregas se guardan solo en este navegador; no se crean usuarios ni se envían datos en línea.'}</div><div class="activity-role-switch"><button class="${activitiesView==='teacher'?'active':''}" data-activity-view="teacher"><span>♧</span> Vista docente</button><button class="${activitiesView==='student'?'active':''}" data-activity-view="student"><span>♙</span> Vista estudiante</button></div>${activitiesView==='teacher'?teacherActivitiesPage():studentActivitiesPage()}`}
function teacherActivitiesPage(){const tasks=(data.tasks||[]).slice().sort((a,b)=>Number(b.id)-Number(a.id));return `<section class="activity-intro"><div><span class="eyebrow">AULA CLARA · ACTIVIDADES</span><h2>Prepará una consigna para tu división.</h2><p>Elegí un modelo, asignalo a un curso y seguí las entregas desde este espacio.</p></div><div class="activity-intro-mark">✳</div></section><div class="activity-type-grid">${Object.keys(activityTypes).map(activityCard).join('')}</div><section class="panel assigned-activities"><div class="panel-heading"><div><h3>Actividades asignadas</h3><p>Consignas publicadas en este dispositivo</p></div><span class="school-year">${tasks.length} ${tasks.length===1?'actividad':'actividades'}</span></div>${tasks.length?`<div class="activity-task-list">${tasks.map(t=>{const responses=(data.taskResponses||[]).filter(r=>String(r.taskId)===String(t.id));const roster=data.students.filter(s=>s.grade===t.grade&&s.division===t.division).length;return `<article class="activity-task-row"><div class="task-type-symbol ${esc(t.type)}">${activityTypes[t.type]?.icon||'▣'}</div><div class="task-row-info"><b>${esc(t.title)}</b><small>${esc(activityTypes[t.type]?.label||'Actividad')} · ${esc(t.grade)} ${esc(t.division)} · ${roster} estudiantes</small></div><div class="task-progress"><b>${responses.length}/${roster}</b><small>entregas</small></div><button class="button secondary small" data-task-results="${esc(t.id)}">Ver entregas</button></article>`}).join('')}</div>`:'<div class="activity-empty-inline"><span>▣</span><b>Todavía no hay actividades asignadas.</b><small>Elegí uno de los modelos para publicar la primera consigna.</small></div>'}</section>`}
function studentActivitiesPage(){const students=data.students.slice().sort((a,b)=>a.name.localeCompare(b.name,'es'));if(!students.length)return `<section class="panel empty-state"><h3>No hay estudiantes de muestra</h3><p>Agregá un estudiante para probar esta vista.</p><button class="button primary small" data-add="student">Agregar alumno</button></section>`;if(!selectedActivityStudent||!students.some(s=>String(s.id)===String(selectedActivityStudent)))selectedActivityStudent=String(students[0].id);const student=students.find(s=>String(s.id)===String(selectedActivityStudent));const assigned=(data.tasks||[]).filter(t=>t.grade===student.grade&&t.division===student.division).sort((a,b)=>Number(b.id)-Number(a.id));const done=assigned.filter(t=>(data.taskResponses||[]).some(r=>String(r.taskId)===String(t.id)&&String(r.studentId)===String(student.id)));const pending=assigned.filter(t=>!done.includes(t));return `<div class="student-task-toolbar"><div><span class="eyebrow">MI ESPACIO DE APRENDIZAJE</span><h2>Hola, ${esc(student.name.split(' ')[0])}.</h2><p>Estas son las actividades para ${esc(student.grade)} ${esc(student.division)}.</p></div><label for="activityStudentSelect">Probar como<select class="filter-select" id="activityStudentSelect">${students.map(s=>`<option value="${esc(s.id)}" ${String(s.id)===String(student.id)?'selected':''}>${esc(s.name)} · ${esc(s.grade)} ${esc(s.division)}</option>`).join('')}</select></label></div><div class="student-task-counts"><div><b>${pending.length}</b><span>Pendientes</span></div><div><b>${done.length}</b><span>Completadas</span></div></div><section class="student-tasks-section"><div class="panel-heading"><div><h3>Para hacer</h3><p>Elegí una actividad para comenzar</p></div></div>${pending.length?`<div class="student-task-grid">${pending.map(t=>studentTaskCard(t,false)).join('')}</div>`:'<div class="activity-empty-inline"><span>✓</span><b>¡Estás al día!</b><small>Cuando tu docente asigne una actividad, va a aparecer acá.</small></div>'}</section>${done.length?`<section class="student-tasks-section completed-section"><div class="panel-heading"><div><h3>Completadas</h3><p>Tus actividades enviadas</p></div></div><div class="student-task-grid">${done.map(t=>studentTaskCard(t,true)).join('')}</div></section>`:''}`}
function studentTaskCard(task,completed){const type=activityTypes[task.type]||activityTypes.comprehension;const response=(data.taskResponses||[]).find(r=>String(r.taskId)===String(task.id)&&String(r.studentId)===String(selectedActivityStudent));return `<article class="student-task-card ${completed?'is-complete':''}"><div class="student-task-card-top"><span class="task-type-symbol ${esc(task.type)}">${type.icon}</span><span class="${completed?'status-chip':'due-chip'}">${completed?'Entregada':task.dueDate?`Hasta ${esc(task.dueDate)}`:'Pendiente'}</span></div><span class="activity-level">${esc(type.label)} · ${esc(task.grade)} ${esc(task.division)}</span><h3>${esc(task.title)}</h3><p>${esc(task.instructions||type.prompt)}</p>${completed?`<div class="student-score">${response.score===null?'Entrega registrada':`Resultado de la actividad: ${response.score}/${response.scoreMax}`}</div>`:`<button class="button primary small" data-take-task="${esc(task.id)}">Comenzar actividad →</button>`}</article>`}
function openAssignActivity(type){if(!activityTypes[type])return;if(!data.classes.length){toast('Primero creá una división para asignar la actividad.');return}const template=activityTypes[type];$('#modalRoot').innerHTML=`<div class="modal-backdrop"><section class="modal activity-assign-modal"><div class="modal-header"><div><h2>Asignar ${esc(template.label.toLowerCase())}</h2><p>La consigna va a quedar disponible para todo el curso.</p></div><button type="button" class="modal-close" data-close-activity>×</button></div><form id="assignActivityForm" data-type="${esc(type)}"><div class="activity-template-preview"><span class="activity-type-icon ${esc(type)}">${template.icon}</span><div><b>${esc(template.title)}</b><small>Material original · adaptable por el docente</small></div></div><div class="field"><label for="taskClass">Curso y división</label><select id="taskClass" name="classId" required>${data.classes.map(c=>`<option value="${esc(c.id)}">${esc(c.grade)} ${esc(c.division)} · ${esc(c.level)} · ${esc(c.shift)}</option>`).join('')}</select></div><div class="field"><label for="taskTitle">Título de la actividad</label><input id="taskTitle" name="title" value="${esc(template.title)}" maxlength="100" required></div><div class="field"><label for="taskInstructions">Consigna para el grupo</label><textarea id="taskInstructions" name="instructions" rows="3" maxlength="600">${esc(template.prompt)}</textarea></div><div class="field"><label for="taskDue">Fecha sugerida de entrega (opcional)</label><input id="taskDue" name="dueDate" type="date" min="${new Date().toISOString().slice(0,10)}"></div><div class="modal-actions"><button type="button" class="button secondary small" data-close-activity>Cancelar</button><button class="button primary small" type="submit">Asignar al curso</button></div></form></section></div>`;document.querySelectorAll('[data-close-activity]').forEach(b=>b.onclick=closeModal);$('.modal-backdrop').onclick=e=>{if(e.target.classList.contains('modal-backdrop'))closeModal()}}
function beginTask(id){const task=(data.tasks||[]).find(t=>String(t.id)===String(id));if(!task)return;activeActivityId=task.id;activeTaskStartedAt=Date.now();currentPage='actividad-realizar';document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.page==='actividades'));$('#breadcrumbPage').textContent=pageLabels[currentPage];render()}
function activityRunnerPage(){const task=(data.tasks||[]).find(t=>String(t.id)===String(activeActivityId));const student=data.students.find(s=>String(s.id)===String(selectedActivityStudent));if(!task||!student){currentPage='actividades';return activitiesPage()}const type=activityTypes[task.type];return `${heading(task.title,`${type.label} · ${esc(student.name)} · ${esc(task.grade)} ${esc(task.division)}`,`<button class="button secondary small" data-return-activities>← Volver a mis actividades</button>`)}<section class="notice-card"><span class="notice-icon">i</span><p>Trabajá a tu ritmo. ${AulaClaraState?.cloudSession?'Al enviar, el registro se guarda en el colegio asociado a la cuenta docente. El acceso individual de estudiantes todavía está pendiente.':'Al enviar, tu respuesta quedará guardada en este navegador para que el docente pueda revisarla.'}</p></section><form id="studentTaskForm" novalidate class="panel student-task-form" data-task-id="${esc(task.id)}" data-type="${esc(task.type)}"><div class="task-instructions"><span class="eyebrow">CONSIGNA</span><p>${esc(task.instructions||type.prompt)}</p></div>${activityTaskContent(task.type)}<div class="student-submit-row"><span>Revisá tu respuesta antes de enviarla.</span><button class="button primary" type="submit" data-submit-task>Enviar actividad</button></div></form>`}
function activityTaskContent(type){if(type==='oral')return `<div class="task-reading-text"><h3>${esc(activityTypes.oral.title)}</h3><p>${esc(activityTypes.oral.text)}</p></div><label class="task-check"><input type="checkbox" name="readComplete" value="yes" required> Leí el texto en voz alta hasta el final.</label>`;if(type==='comprehension')return `<div class="task-reading-text"><h3>${esc(activityTypes.comprehension.title)}</h3><p>${esc(activityTypes.comprehension.text)}</p></div>${activityQuestions.map((q,i)=>`<fieldset class="task-question"><legend>${i+1}. ${esc(q.text)}</legend>${q.options.map(([value,label])=>`<label><input type="radio" name="${q.key}" value="${value}" required> ${esc(label)}</label>`).join('')}</fieldset>`).join('')}`;if(type==='writing')return `<div class="writing-prompt-box"><span>✎</span><p>${esc(activityTypes.writing.prompt)}</p></div><div class="field"><label for="studentWriting">Mi texto</label><textarea id="studentWriting" name="studentWriting" rows="9" minlength="30" maxlength="5000" placeholder="Escribí acá tus ideas..." required></textarea><small>Escribí al menos 30 caracteres. Tu docente va a leer tu producción.</small></div>`;return `<div class="math-task-grid">${mathQuestions.map(([key,question])=>`<label class="math-question"><span>${esc(question)}</span><input type="number" name="${key}" required aria-label="Respuesta de ${esc(question)}"></label>`).join('')}</div><div class="field"><label for="mathNotes">¿Cómo lo resolviste? (opcional)</label><textarea id="mathNotes" name="mathNotes" rows="3" maxlength="1000" placeholder="Podés contar o mostrar tu procedimiento..."></textarea></div>`}
function submitTask(e){
  e.preventDefault();
  const form=e.currentTarget,type=form.dataset.type,task=(data.tasks||[]).find(t=>String(t.id)===String(form.dataset.taskId)),student=data.students.find(s=>String(s.id)===String(selectedActivityStudent));
  if(!task||!student){toast('No encontramos la actividad o el estudiante. Volvé a Actividades y elegí el curso correcto.');return}
  const fd=new FormData(form),answers={};for(const [k,v]of fd.entries())answers[k]=String(v);
  if(type==='oral'&&answers.readComplete!=='yes'){toast('Marcá la casilla para confirmar que terminaste la lectura.');return}
  if(type==='comprehension'&&activityQuestions.some(q=>!answers[q.key])){toast('Respondé las tres preguntas antes de enviar.');return}
  if(type==='math'&&mathQuestions.some(([key])=>answers[key]===undefined||answers[key]===''||!Number.isFinite(Number(answers[key])))){toast('Completá las cuatro respuestas de matemática antes de enviar.');return}
  if(type==='writing'&&String(answers.studentWriting||'').trim().length<30){toast('Escribí al menos 30 caracteres antes de enviar tu producción.');form.querySelector('#studentWriting')?.focus();return}
  let score=null,scoreMax=null,text='';const response={};
  if(type==='comprehension'){score=activityQuestions.reduce((n,q)=>n+(answers[q.key]===q.answer?1:0),0);scoreMax=activityQuestions.length}
  if(type==='math'){score=mathQuestions.reduce((n,[key,,answer])=>n+(Number(answers[key])===answer?1:0),0);scoreMax=mathQuestions.length;response.observations=String(answers.mathNotes||'')}
  if(type==='writing')text=String(answers.studentWriting||'').trim();
  if(type==='oral')response.completedReading=answers.readComplete==='yes';
  response.answers=answers;response.studentText=text;
  const elapsedSeconds=activeTaskStartedAt?Math.max(1,Math.round((Date.now()-activeTaskStartedAt)/1000)):null;
  const record={id:Date.now(),taskId:task.id,studentId:student.id,studentName:student.name,submittedAt:new Date().toISOString(),elapsedSeconds,score,scoreMax,...response};
  const previous=(data.taskResponses||[]).findIndex(r=>String(r.taskId)===String(task.id)&&String(r.studentId)===String(student.id));
  if(previous>=0)data.taskResponses[previous]=record;else data.taskResponses.push(record);
  setActivity(`${student.name} entregó la actividad «${task.title}».`);
  activeActivityId=null;activeTaskStartedAt=null;activitiesView='student';currentPage='actividades';render();toast('Actividad enviada. Ya aparece en “Completadas”.');
}
function showTaskResults(taskId){const task=(data.tasks||[]).find(t=>String(t.id)===String(taskId));if(!task)return;const responses=(data.taskResponses||[]).filter(r=>String(r.taskId)===String(taskId));const roster=data.students.filter(s=>s.grade===task.grade&&s.division===task.division);const report=taskPerformanceSummary(task,responses);const rows=roster.map(s=>{const r=responses.find(x=>String(x.studentId)===String(s.id));return `<div class="teacher-response-row"><span class="person-initial">${initials(esc(s.name))}</span><div><b>${esc(s.name)}</b><small>${r?`Entregada · ${new Intl.DateTimeFormat('es-AR',{dateStyle:'short',timeStyle:'short'}).format(new Date(r.submittedAt))}`:'Pendiente'}</small></div><strong>${r?(r.score===null?'Entregada':`${r.score}/${r.scoreMax}`):'—'}</strong>${r&&r.studentText?`<details><summary>Leer producción</summary><p>${esc(r.studentText)}</p></details><button class="button secondary small writing-review-button" data-writing-review="${esc(task.id)}:${esc(s.id)}">${r.writingReview?'Editar revisión docente':'Abrir guía de revisión'}</button>${r.writingReview?`<small class="writing-review-saved">Revisión docente guardada · ${esc(r.writingReview.date||'')}</small><details class="writing-review-report"><summary>Ver informe de revisión</summary><h4>Estructura y organización · ${esc(r.writingReview.structureStatus||'')}</h4><p>${esc(r.writingReview.structureNote||'Sin observación registrada.')}</p><h4>Recursos del lenguaje · ${esc(r.writingReview.languageStatus||'')}</h4><p>${esc(r.writingReview.languageNote||'Sin observación registrada.')}</p><h4>Escritura y presentación · ${esc(r.writingReview.mechanicsStatus||'')}</h4><p>${esc(r.writingReview.mechanicsNote||'Sin observación registrada.')}</p><b>Próximo paso</b><p>${esc(r.writingReview.nextStep||'Sin sugerencia registrada.')}</p></details>`:''}`:''}${r&&r.observations?`<details><summary>Ver procedimiento</summary><p>${esc(r.observations)}</p></details>`:''}</div>`}).join('');$('#modalRoot').innerHTML=`<div class="modal-backdrop"><section class="modal task-results-modal"><div class="modal-header"><div><h2>${esc(task.title)}</h2><p>${esc(activityTypes[task.type].label)} · ${esc(task.grade)} ${esc(task.division)} · ${responses.length}/${roster.length} entregas</p></div><button type="button" class="modal-close" data-close-task-results>×</button></div><p class="teacher-results-note">Las respuestas automáticas son orientativas. Revisá cada producción en contexto.</p>${report}<div class="teacher-response-list">${rows||'<p class="table-empty">No hay estudiantes en esta división.</p>'}</div><div class="modal-actions"><button type="button" class="button secondary small" data-close-task-results>Cerrar</button></div></section></div>`;document.querySelectorAll('[data-close-task-results]').forEach(b=>b.onclick=closeModal);$('.modal-backdrop').onclick=e=>{if(e.target.classList.contains('modal-backdrop'))closeModal()}}
document.addEventListener('change',e=>{if(e.target?.id==='activityStudentSelect'){selectedActivityStudent=e.target.value;activeActivityId=null;render()}});
document.addEventListener('click',e=>{if(e.target.closest('[data-return-activities]')){activeActivityId=null;activitiesView='student';navigate('actividades')}});
document.addEventListener('submit',e=>{
  if(e.target?.id==='assignActivityForm'){
    e.preventDefault();const type=e.target.dataset.type,formData=new FormData(e.target),cl=data.classes.find(c=>String(c.id)===String(formData.get('classId')));if(!cl)return;
    const task={id:Date.now(),type,title:String(formData.get('title')).trim(),instructions:String(formData.get('instructions')||'').trim(),dueDate:String(formData.get('dueDate')||''),grade:cl.grade,division:cl.division,level:cl.level,createdAt:new Date().toISOString()};
    data.tasks.push(task);setActivity(`Se asignó «${task.title}» a ${cl.grade} ${cl.division}.`);closeModal();render();toast('Actividad asignada al curso.');
  }
  if(e.target?.id==='studentTaskForm')submitTask(e);
});

function taskPerformanceSummary(task,responses){
  if(!responses.length)return '';
  const completed=responses.filter(r=>Number.isFinite(Number(r.elapsedSeconds))&&Number(r.elapsedSeconds)>0),avg=completed.length?Math.round(completed.reduce((n,r)=>n+Number(r.elapsedSeconds),0)/completed.length):null;
  const total=responses.reduce((n,r)=>n+(Number(r.score)||0),0),possible=responses.reduce((n,r)=>n+(Number(r.scoreMax)||0),0),accuracy=possible?Math.round(total/possible*100):null;
  const summary=`<section class="task-report-summary"><div class="task-report-top"><div><span>RESULTADOS DEL GRUPO</span><h3>${accuracy===null?'Producciones recibidas':`${accuracy}% de respuestas correctas`}</h3></div><div class="task-report-metrics"><div><b>${responses.length}</b><small>entregas</small></div><div><b>${avg===null?'—':`${avg}s`}</b><small>${avg===null?'tiempo no registrado':'promedio por tarea'}</small></div></div></div>${task.type==='math'?`<div class="task-category-grid">${mathQuestions.map(([key,label,answer])=>{const correct=responses.filter(r=>Number(r.answers?.[key])===answer).length,pct=Math.round(correct/responses.length*100);return `<div class="task-category"><div><b>${esc(label)}</b><span>${correct}/${responses.length} correctas</span></div><div class="task-category-bar"><i style="width:${pct}%"></i></div><small>${pct}% de respuestas correctas · descriptivo</small></div>`}).join('')}</div>`:''}${task.type==='comprehension'?`<div class="task-category-grid">${activityQuestions.map(q=>{const correct=responses.filter(r=>r.answers?.[q.key]===q.answer).length,pct=Math.round(correct/responses.length*100);return `<div class="task-category"><div><b>${esc(q.text)}</b><span>${correct}/${responses.length}</span></div><div class="task-category-bar"><i style="width:${pct}%"></i></div><small>${pct}% de respuestas correctas · esta consigna</small></div>`}).join('')}</div>`:''}<small class="task-report-caveat">Descripción de esta tarea y este grupo. No es un baremo ni una interpretación diagnóstica.</small></section>`;
  return summary;
}

document.addEventListener('click',e=>{const b=e.target.closest('[data-writing-review]');if(!b)return;const [taskId,studentId]=b.dataset.writingReview.split(':');openWritingReview(taskId,studentId)});
function openWritingReview(taskId,studentId){const r=(data.taskResponses||[]).find(x=>String(x.taskId)===String(taskId)&&String(x.studentId)===String(studentId));if(!r)return;const review=r.writingReview||{};const sections=[['structure','Estructura y organización','Secuencia de ideas, inicio/desarrollo/cierre y coherencia.'],['language','Recursos del lenguaje','Vocabulario, conectores, voz y construcción de oraciones.'],['mechanics','Escritura y presentación','Ortografía, puntuación, legibilidad y convenciones.']];const statusOptions=['Aún sin revisar','Se observa','En desarrollo','Fortaleza'];$('#modalRoot').innerHTML=`<div class="modal-backdrop"><section class="modal writing-review-modal"><div class="modal-header"><div><span class="eyebrow">REVISIÓN DOCENTE · PRODUCCIÓN ESCRITA</span><h2>${esc(r.studentName)}</h2><p>Estas observaciones son aportadas por el docente y se guardan en este dispositivo.</p></div><button class="modal-close" type="button" data-close-writing-review>×</button></div><details class="writing-review-evidence"><summary>Ver texto entregado</summary><p>${esc(r.studentText||'Sin texto disponible')}</p></details><form id="writingReviewForm" data-task-id="${esc(taskId)}" data-student-id="${esc(studentId)}">${sections.map(([key,title,help])=>`<section class="writing-review-section"><div><h3>${title}</h3><p>${help}</p></div><label>Estado<select name="${key}Status">${statusOptions.map(x=>`<option ${review[key+'Status']===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Observación basada en la producción<textarea name="${key}Note" rows="2" maxlength="500" placeholder="Anotá una evidencia concreta del texto...">${esc(review[key+'Note']||'')}</textarea></label></section>`).join('')}<div class="field"><label for="writingNextStep">Sugerencia o próximo paso acordado</label><textarea id="writingNextStep" name="nextStep" rows="3" maxlength="600" placeholder="Una propuesta concreta para acompañar la próxima producción...">${esc(review.nextStep||'')}</textarea></div><div class="writing-review-disclaimer">Guía de revisión pedagógica; no es análisis automático ni evaluación diagnóstica. Para interpretar caligrafía desde una foto y detectar posibles errores automáticamente falta integrar IA y carga privada de imágenes.</div><div class="modal-actions"><button type="button" class="button secondary small" data-close-writing-review>Cancelar</button><button type="submit" class="button primary small">Guardar revisión</button></div></form></section></div>`;document.querySelectorAll('[data-close-writing-review]').forEach(x=>x.onclick=closeModal);$('#writingReviewForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget),review={};for(const [k,v]of fd.entries())review[k]=String(v).trim();review.date=new Intl.DateTimeFormat('es-AR').format(new Date());r.writingReview=review;save();closeModal();showTaskResults(taskId);toast('Revisión docente guardada.')}}
