let csvImportPreview=[];

function openEditItem(key){
  const [type,id]=key.split(':');
  const list=type==='student'?data.students:type==='teacher'?data.teachers:type==='class'?data.classes:[];
  const item=list.find(x=>String(x.id)===String(id));if(!item)return;
  openModal(type);const form=document.querySelector('#entityForm');form.dataset.editId=String(item.id);
  document.querySelector('.modal-header h2').textContent=type==='student'?'Editar alumno':type==='teacher'?'Editar docente':'Editar división';
  document.querySelector('.modal-header p').textContent='Actualizá la información y guardá los cambios.';
  const submit=form.querySelector('button[type="submit"]');if(submit)submit.textContent='Guardar cambios';
  Object.entries(item).forEach(([name,value])=>{const field=form.elements.namedItem(name);if(field&&typeof value==='string')field.value=value});
}

function openStudentImport(){
  csvImportPreview=[];
  document.querySelector('#modalRoot').innerHTML=`<div class="modal-backdrop"><section class="modal csv-import-modal"><div class="modal-header"><div><h2>Importar alumnos desde CSV</h2><p>Subí una lista para agregar varios estudiantes de una vez.</p></div><button type="button" class="modal-close" data-close-import>×</button></div><div class="csv-format-note"><b>Columnas necesarias:</b> nombre, curso, division. También podés incluir apellido y email. Acepta coma o punto y coma como separador. El archivo se procesa solo en este navegador.<br><a href="online-pilot/alumnos-ejemplo.csv" download>Descargar archivo de ejemplo</a></div><div class="field csv-file-field"><label for="csvFile">Archivo CSV</label><input id="csvFile" type="file" accept=".csv,text/csv"><small>Hasta 2 MB y 500 filas de estudiantes.</small></div><div id="csvPreview"></div><div class="modal-actions"><button type="button" class="button secondary small" data-close-import>Cancelar</button><button type="button" class="button primary small" id="confirmCsvImport" disabled>Importar alumnos</button></div></section></div>`;
  document.querySelectorAll('[data-close-import]').forEach(b=>b.onclick=closeModal);
  document.querySelector('.modal-backdrop').onclick=e=>{if(e.target.classList.contains('modal-backdrop'))closeModal()};
  document.querySelector('#csvFile').onchange=previewStudentCsv;
  document.querySelector('#confirmCsvImport').onclick=commitStudentCsv;
}

function parseCsvRows(text,delimiter){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const char=text[i];if(char==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(char===delimiter&&!quoted){row.push(cell.trim());cell=''}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&text[i+1]==='\n')i++;row.push(cell.trim());if(row.some(value=>value!==''))rows.push(row);row=[];cell=''}else cell+=char}row.push(cell.trim());if(row.some(value=>value!==''))rows.push(row);return rows}
function normalizeHeader(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[\s_-]+/g,'')}
function previewStudentCsv(e){const file=e.target.files?.[0],preview=document.querySelector('#csvPreview'),button=document.querySelector('#confirmCsvImport');csvImportPreview=[];button.disabled=true;if(!file)return;if(file.size>2*1024*1024){preview.innerHTML='<p class="csv-error">El archivo supera el límite de 2 MB.</p>';return}file.text().then(text=>{text=text.replace(/^\uFEFF/,'');const firstLine=text.split(/\r?\n/,1)[0]||'';const delimiter=(firstLine.match(/;/g)||[]).length>(firstLine.match(/,/g)||[]).length?';':',';const rows=parseCsvRows(text,delimiter);if(rows.length<2){preview.innerHTML='<p class="csv-error">El archivo no tiene filas de datos.</p>';return}if(rows.length>501){preview.innerHTML='<p class="csv-error">El archivo supera las 500 filas permitidas.</p>';return}const headers=rows.shift().map(normalizeHeader),column=names=>headers.findIndex(h=>names.includes(h));const nameCol=column(['nombre','name','alumno','estudiante']),lastCol=column(['apellido','apellidos','lastname','surname']),gradeCol=column(['curso','grado','ano','year','grade']),divisionCol=column(['division','seccion','section']),emailCol=column(['email','correo','correoelectronico']);if(nameCol<0||gradeCol<0||divisionCol<0){preview.innerHTML='<p class="csv-error">No encontramos las columnas obligatorias nombre, curso y division.</p>';return}const valid=[],errors=[];rows.forEach((row,index)=>{const name=(row[nameCol]||'').trim(),last=lastCol>=0?(row[lastCol]||'').trim():'',grade=(row[gradeCol]||'').trim(),division=(row[divisionCol]||'').trim().toUpperCase(),email=emailCol>=0?(row[emailCol]||'').trim():'';if(!name){errors.push(`Fila ${index+2}: falta el nombre.`);return}const cls=data.classes.find(c=>normalizeHeader(c.grade)===normalizeHeader(grade)&&normalizeHeader(c.division)===normalizeHeader(division));if(!cls){errors.push(`Fila ${index+2}: no existe el curso ${grade} ${division}.`);return}if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){errors.push(`Fila ${index+2}: el correo no parece válido.`);return}valid.push({name:[name,last].filter(Boolean).join(' '),email,grade:cls.grade,division:cls.division})});csvImportPreview=valid;button.disabled=!valid.length;preview.innerHTML=`<div class="csv-preview-summary"><b>${valid.length} alumnos listos para importar</b><span>${errors.length} filas con observaciones</span></div>${errors.length?`<ul class="csv-errors">${errors.slice(0,6).map(error=>`<li>${esc(error)}</li>`).join('')}${errors.length>6?`<li>y ${errors.length-6} más…</li>`:''}</ul>`:''}${valid.length?`<div class="csv-preview-sample">${valid.slice(0,3).map(s=>`<span>${esc(s.name)} · ${esc(s.grade)} ${esc(s.division)}</span>`).join('')}</div>`:''}`}).catch(()=>{preview.innerHTML='<p class="csv-error">No pudimos leer el archivo. Guardalo como CSV e intentá otra vez.</p>'})}
function commitStudentCsv(){if(!csvImportPreview.length)return;const imported=csvImportPreview.map((student,index)=>({id:Date.now()+index,...student,status:'Activo'}));data.students.push(...imported);setActivity(`Se importaron ${imported.length} alumnos desde un archivo CSV.`);closeModal();render();toast(`${imported.length} alumnos importados.`)}
